version: '3'
services:
  tomcat:
    image: tomcat:9.0
    container_name: aplicacionjava
    volumes: 
      - ./sample.war:/usr/local/tomcat/webapps/sample.war
  proxy:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

networks:
  default:
    name: xarxa-compose